{"uuid":"09d201fb-0574-4521-83d9-3396c21015c6","historyId":"5dcef28b920be5fcb77c7d5d5f3486c9","status":"passed","statusDetails":null,"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138872051,"name":"visit / -> 302: https://opensource-demo.orangehrmlive.com/web/index.php/auth/login","stop":1692138872864},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138872864,"name":"GET --- /web/index.php/core/i18n/messages","stop":1692138872864},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138872864,"name":"fixture (\"example\")","stop":1692138872873},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138873878,"name":"get :nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input","stop":1692138873893}],"attachments":[],"parameters":[],"start":1692138872907,"name":"get :nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input","stop":1692138873894},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138873894,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.get()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138873894}],"attachments":[],"parameters":[],"start":1692138872878,"name":"get function(){}","stop":1692138873894},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138873894,"name":"assert expected **<document>** to be **visible**","stop":1692138873894},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138873907,"name":"type Admin","stop":1692138874289},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138874316,"name":"get :nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input","stop":1692138874330}],"attachments":[],"parameters":[],"start":1692138874289,"name":"get function(){}","stop":1692138874331},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138874331,"name":"assert expected **<document>** to be **visible**","stop":1692138874331},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138874768,"name":"get :nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input","stop":1692138874800}],"attachments":[],"parameters":[],"start":1692138874341,"name":"type admin123","stop":1692138874800},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138874800,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.type()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138874800},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138874800,"name":"get .oxd-button","stop":1692138874816},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138874816,"name":"click","stop":1692138875152},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138875150,"name":"page load --waiting for new page to load--","stop":1692138875150}],"attachments":[],"parameters":[],"start":1692138872876,"name":"login (\"Admin\"; \"admin123\")","stop":1692138875152},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138875152,"name":"new url https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index","stop":1692138876525},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138876524,"name":"GET --- /web/index.php/core/i18n/messages","stop":1692138876524},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138876525,"name":"get function(){}","stop":1692138876525},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138877173,"name":"get .oxd-topbar-header-breadcrumb > .oxd-text","stop":1692138877187}],"attachments":[],"parameters":[],"start":1692138876525,"name":"contains Dashboard","stop":1692138877188},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138877188,"name":"GET --- /web/index.php/api/v2/dashboard/employees/action-summary","stop":1692138877188},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138877188,"name":"GET --- /web/index.php/api/v2/dashboard/shortcuts","stop":1692138877188},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138877188,"name":"GET --- /web/index.php/api/v2/buzz/feed?limit=5&offset=0&sortOrder=DESC&sortField=share.createdAtUtc","stop":1692138877188},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138877188,"name":"GET --- /web/index.php/api/v2/dashboard/employees/subunit","stop":1692138877188},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138877188,"name":"GET --- /web/index.php/api/v2/dashboard/employees/locations","stop":1692138877188},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138877188,"name":"POST --- /web/index.php/events/push","stop":1692138877188},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138877188,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.contains()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138877188},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138877188,"name":"contains Invalid credentials","stop":1692138877198},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"actual","value":":cy-contains(**'Invalid credentials'**), [type=**'submit'**][value~=**'Invalid credentials'**]"},{"name":"expected","value":":cy-contains('Invalid credentials'), [type='submit'][value~='Invalid credentials']"}],"start":1692138877198,"name":"assert expected **:cy-contains(**'Invalid credentials'**), [type=**'submit'**][value~=**'Invalid credentials'**]** not to exist in the DOM","stop":1692138877198},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138877198,"name":"url","stop":1692138877221},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"actual","value":"https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index"},{"name":"expected","value":"https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index"}],"start":1692138877221,"name":"assert expected **https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index** to equal **https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index**","stop":1692138877221}],"attachments":[],"parameters":[],"start":1692138870070,"name":"\"before each\" hook","stop":1692138877222},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138877298,"name":"wait 2000","stop":1692138879320},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138879321,"name":"get .oxd-userdropdown-tab","stop":1692138879329},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138879329,"name":"click","stop":1692138879549},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138879549,"name":"get :nth-child(4) > .oxd-userdropdown-link","stop":1692138879560},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138879560,"name":"click","stop":1692138879735},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138879735,"name":"page load --waiting for new page to load--","stop":1692138879735}],"attachments":[],"parameters":[],"start":1692138877224,"name":"logout","stop":1692138879735},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138879735,"name":"new url https://opensource-demo.orangehrmlive.com/web/index.php/auth/login","stop":1692138880861},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138880860,"name":"GET --- /web/index.php/core/i18n/messages","stop":1692138880860},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138880861,"name":"url","stop":1692138880861},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"actual","value":"https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"},{"name":"expected","value":"https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"}],"start":1692138880861,"name":"assert expected **https://opensource-demo.orangehrmlive.com/web/index.php/auth/login** to equal **https://opensource-demo.orangehrmlive.com/web/index.php/auth/login**","stop":1692138880861},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138880861,"name":"get function(){}","stop":1692138880865},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138881410,"name":"get .oxd-text--h5","stop":1692138881420}],"attachments":[],"parameters":[],"start":1692138880865,"name":"contains Login","stop":1692138881420},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692138881420,"name":"uncaught exception CypressError: Cypress detected that you returned a promise from a command while also invoking one or more cy commands in that promise.\n\nThe command that returned the promise was:\n\n  > `cy.contains()`\n\nThe cy command you invoked inside the promise was:\n\n  > `cy.get()`\n\nBecause Cypress commands are already promise-like, you don't need to wrap them or return your own promise.\n\nCypress will resolve your command with whatever the final Cypress command yields.\n\nThe reason this is an error instead of a warning is because Cypress internally queues commands serially whereas Promises execute as soon as they are invoked. Attempting to reconcile this would prevent Cypress from ever resolving.","stop":1692138881420}],"attachments":[],"parameters":[],"labels":[{"name":"package","value":"cypress.integration.test-spec.js"},{"name":"suite","value":"Test Logout Functionality"}],"links":[],"start":1692138870065,"name":"should logout a user","fullName":"should logout a user","stop":1692138881429}